version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: echo "Running tests"
      - run: yarn install
      - run: yarn test

  build:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: echo "Build project"
      - run: yarn install
      - run: yarn build

workflows:
  test_build:
    jobs:
      - test
      - build:
          requires:
            - test
