version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14
        environment:
          NODE_ENV: test
          APP_PORT: 3000
          APP_HOST: localhost
          AWS_REGION: eu-west-3
          DATABASE_URL: postgresql://admin:password@localhost:5432/postgres?schema=public
          JWT_PUBLIC_KEY: $JWT_PUBLIC_KEY
          JWT_PRIVATE_KEY: $JWT_PRIVATE_KEY
          JWT_ACCESS_TOKEN_EXPIRATION_TIME: 86400
          JWT_REFRESH_TOKEN_EXPIRATION_TIME: 2592000
          ENCRYPTION_KEY: xxx-xxx-xxx

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: postgres
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password

    steps:
      - name: Running tests
      - run: yarn install
      - run: yarn test

  build:
    docker:
      - image: circleci/node:14

    steps:
      - name: Build project
      - run: yarn install
      - run: yarn build

workflows:
  test_build:
    jobs:
      - test
      - build:
          requires:
            - test
