name: CI-FEATURES

on:
  workflow_dispatch:
  push:
    branches:
      - '*' # matches every branch that doesn't contain a '/'
      - '*/*' # matches every branch containing a single '/'
      - '**' # matches every branch
      - '!main' # excludes main
      - '!dev' # excludes dev

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      AWS_KEY_REGION: eu-west-3
      DATABASE_URL: postgresql://admin:password@localhost:5432/postgres?schema=public
      JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
      JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
      ASSETS_CDN_URL: https://test-domain-name.cloudfront.net
      DOMAIN_URL: https://test-domain-name.com
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      # Setup
      - name: Actions checkout
        uses: actions/checkout@v2

      - name: Set up node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      # Build
      - name: Install packages
        run: yarn

      - name: Build app
        run: yarn build

      # Test
      - name: Test app
        run: yarn test
