name: CI-PREPROD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Actions checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      # Build
      - name: Install packages
        run: yarn

      - name: Build app
        run: yarn build

      # Test
      - name: Create docker database
        run: yarn database:create

      - name: Test app
        run: yarn test:e2e
        env:
          NODE_ENV: test
          APP_PORT: 3000
          APP_HOST: localhost
          AWS_REGION: eu-west-3
          DATABASE_URL: postgresql://postgres:password@localhost:5432/postgres?schema=public
          JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
          JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
          JWT_ACCESS_TOKEN_EXPIRATION_TIME: 86400
          JWT_REFRESH_TOKEN_EXPIRATION_TIME: 2592000
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
